CREATE TYPE IF NOT EXISTS "mpa_title" AS ENUM (
    'G',
    'PG',
    'PG-13',
    'R',
    'NC-17'
    );

CREATE TABLE IF NOT EXISTS "mpa_rating"
(
    "mpa_id"   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mpa_name" "mpa_title" UNIQUE
);

CREATE TYPE IF NOT EXISTS "genre_title" AS ENUM (
    'Комедия',
    'Драма',
    'Мультфильм',
    'Триллер',
    'Документальный',
    'Боевик'
    );

CREATE TABLE IF NOT EXISTS "genres"
(
    "genre_id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "genre_name" "genre_title" UNIQUE
);

CREATE TABLE IF NOT EXISTS "directors"
(
    "director_id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "director_name" VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "films"
(
    "film_id"      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "film_name"    VARCHAR      NOT NULL,
    "description"  VARCHAR(200) NOT NULL,
    "release_date" DATE         NOT NULL,
    "duration"     INT          NOT NULL,
    "rate"         INT          NOT NULL,
    "mpa_id"       INT REFERENCES "mpa_rating" ("mpa_id"),
    CONSTRAINT IF NOT EXISTS "not_blank" CHECK (LENGTH("film_name") > 0),
    CONSTRAINT IF NOT EXISTS "earliest_date" CHECK ("release_date" >= CAST('1895-12-28' AS DATE)),
    CONSTRAINT IF NOT EXISTS "positive" CHECK ("duration" > 0)
);

CREATE TABLE IF NOT EXISTS "film_directors"
(
    "film_id"     INT REFERENCES "films" ("film_id") ON DELETE CASCADE,
    "director_id" INT REFERENCES "directors" ("director_id") ON DELETE CASCADE,
    PRIMARY KEY ("film_id", "director_id")
);

CREATE TABLE IF NOT EXISTS "film_genres"
(
    "film_id"  INT REFERENCES "films" ("film_id") ON DELETE CASCADE,
    "genre_id" INT REFERENCES "genres" ("genre_id") ON DELETE CASCADE,
    PRIMARY KEY ("film_id", "genre_id")
);

CREATE TABLE IF NOT EXISTS "users"
(
    "user_id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"     VARCHAR NOT NULL,
    "login"     VARCHAR NOT NULL,
    "user_name" VARCHAR NOT NULL,
    "birthday"  DATE    NOT NULL,
    CONSTRAINT IF NOT EXISTS "not_blank" CHECK (LENGTH("email") > 0 AND LENGTH("login") > 0 AND LENGTH("user_name") > 0),
    CONSTRAINT IF NOT EXISTS "earliest_date" CHECK ("birthday" > CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS "friendships_sent"
(
    "from_user_id" INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "to_user_id"   INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    PRIMARY KEY ("from_user_id", "to_user_id")
);

CREATE TABLE IF NOT EXISTS "likes"
(
    "film_id"      INT REFERENCES "films" ("film_id") ON DELETE CASCADE,
    "from_user_id" INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    PRIMARY KEY ("film_id", "from_user_id")
);

CREATE TABLE IF NOT EXISTS "reviews"
(
    "review_id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "film_id"     INT REFERENCES "films" ("film_id") ON DELETE CASCADE,
    "user_id"     INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "is_positive" BOOLEAN NOT NULL,
    "content"     VARCHAR NOT NULL,
    CONSTRAINT IF NOT EXISTS "not_blank" CHECK (LENGTH("content") > 0)
);

CREATE TABLE IF NOT EXISTS "review_like_dislike"
(
    "review_id" INT REFERENCES "reviews" ("review_id") ON DELETE CASCADE,
    "user_id"   INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "is_like"   BOOLEAN,
    PRIMARY KEY ("review_id", "user_id", "is_like")
);

CREATE TYPE IF NOT EXISTS "event_type" AS ENUM (
    'LIKE',
    'REVIEW',
    'FRIEND'
    );

CREATE TYPE IF NOT EXISTS "operation_type" AS ENUM (
    'REMOVE',
    'ADD',
    'UPDATE'
    );

CREATE TABLE IF NOT EXISTS "feed"
(
    "timestamp" TIMESTAMP NOT NULL,
    "user_id"   INT REFERENCES "users" ("user_id") ON DELETE CASCADE,
    "eventType" "event_type" NOT NULL,
    "operation" "operation_type" NOT NULL,
    "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "entity_id" INT NOT NULL
);